name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install & Predeploy & Test
        timeout_minutes: 1
        max_attempts: 2
        run: |
          yarn install
          yarn predeploy
          yarn test
