name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
        timeout_minutes: 1
        max_attempts: 2
      - run: yarn predeploy
        timeout_seconds: 30
        max_attempts: 2
      - run: yarn test
        timeout_minutes: 5
        max_attempts: 3
